name: Actualizar BD y Publicar en GitHub Pages

on:
  schedule:
    - cron: '30 20 * * 1-5' # Lunes a Viernes a las 17:30 Hora Argentina
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permite correrlo manualmente desde la pestaña Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Instalar dependencias
        run: npm ci
        
      - name: 1. Actualizar TiDB con precios nuevos (Updater)
        run: npm run updater
        
      - name: 2. Congelar BD en un JSON Estático (Build API)
        run: npm run build-api
        
      - name: 3. Compilar Vue Web
        run: npm run build
        
      - name: Subir artefactos web
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4