-- Inserts iniciales de los activos por defecto (Semilla)
INSERT INTO activos (nombre, simbolo, categoria, emoji) VALUES
    ('Dólar Oficial', 'DOLAR_OFICIAL', 'Moneda', '💵'),
    ('Dólar Blue', 'DOLAR_BLUE', 'Moneda', '💵'),
    ('Dólar MEP', 'DOLAR_MEP', 'Moneda', '💵'),
    ('Dólar CCL', 'DOLAR_CCL', 'Moneda', '💵'),
    ('SPDR S&P 500 ETF Trust', 'SPY', 'Índice/ETF', '📈'),
    ('Invesco QQQ Trust', 'QQQ', 'Índice/ETF', '📊'),
    ('Apple Inc.', 'AAPL', 'Big Tech', '🍎'),
    ('Alphabet Inc.', 'GOOGL', 'Big Tech', '🔍'),
    ('Microsoft Corporation', 'MSFT', 'Big Tech', '🪟'),
    ('Nvidia Corporation', 'NVDA', 'Big Tech', '🟩'),
    ('Meta Platforms', 'META', 'Big Tech', '🌐'),
    ('Amazon.com Inc.', 'AMZN', 'Big Tech', '📦'),
    ('Micron Technology', 'MU', 'Wall Street', '💾'),
    ('Taiwan Semiconductor', 'TSM', 'Wall Street', '🏭'),
    ('YPF S.A. (ADR)', 'YPF', 'Merval', '🛢️'),
    ('Grupo Financiero Galicia (ADR)', 'GGAL', 'Merval', '🏦'),
    ('Pampa Energía (ADR)', 'PAM', 'Merval', '⚡'),
    ('Banco Macro (ADR)', 'BMA', 'Merval', '🏛️'),
    ('IRSA Inmuebles (ADR)', 'IRS', 'Real Estate', '🏢'),
    ('Cresud (ADR)', 'CRESY', 'Real Estate', '🏗️'),
    ('Bitcoin USD', 'BTC-USD', 'Cripto', '₿'),
    ('US 10-Year Treasury Yield', '^TNX', 'Bonos', '📜'),
    ('Coca-Cola Company', 'KO', 'Wall Street', '🥤'),
    ('Tesla, Inc.', 'TSLA', 'Wall Street', '🚗'),
    ('The Walt Disney Company', 'DIS', 'Wall Street', '🏰'),
    ('Visa Inc.', 'V', 'Wall Street', '💳'),
    ('Berkshire Hathaway Inc.', 'BRK-B', 'Wall Street', '🏠'),
    ('M2 Núñez', 'M2_NUN', 'Real Estate', '📍'),
    ('M2 Belgrano', 'M2_BEL', 'Real Estate', '📍'),
    ('M2 Palermo', 'M2_PAL', 'Real Estate', '📍'),
    ('M2 Recoleta', 'M2_REC', 'Real Estate', '📍'),
    ('Rendimiento Alquiler', 'ALQ_YIELD', 'Real Estate', '🏠')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre), categoria = VALUES(categoria), emoji = VALUES(emoji);
